export const MATERIAL_PROFILES = {
  asphalt: {
    asset: 'asphalt_02',
    color: 0x404348,
    roughness: .84,
    metalness: 0,
    repeat: [7, 12],
    normalScale: .72,
    wet: { roughness: .16, clearcoat: .88, envMapIntensity: 1.45 },
  },
  roadSurface: {
    asset: 'road001',
    color: 0x4a4a48,
    roughness: .88,
    metalness: 0,
    repeat: [4, 18],
    normalScale: .84,
    wet: { roughness: .18, clearcoat: .82, envMapIntensity: 1.38 },
  },
  concrete: {
    asset: 'brushed_concrete',
    color: 0xa3a7a2,
    roughness: .76,
    metalness: 0,
    repeat: [4, 6],
    normalScale: .46,
    wet: { roughness: .38, clearcoat: .52, envMapIntensity: 1.05 },
  },
  wood: {
    asset: 'brown_planks_03',
    color: 0x856c52,
    roughness: .64,
    metalness: 0,
    repeat: [3, 3],
    normalScale: .58,
    wet: { roughness: .28, clearcoat: .44, envMapIntensity: .92 },
  },
  rock: {
    asset: 'aerial_rocks_04',
    color: 0x73766d,
    roughness: .9,
    metalness: 0,
    repeat: [3, 3],
    normalScale: .9,
    wet: { roughness: .32, clearcoat: .42, envMapIntensity: .98 },
  },
  fieldSurface: {
    asset: 'withered_grass',
    color: 0xa99b69,
    roughness: .91,
    metalness: 0,
    repeat: [10, 18],
    normalScale: 1.05,
    displacementScale: .34,
    displacementBias: -.08,
    wet: { roughness: .42, clearcoat: .22, envMapIntensity: .72 },
  },
  forestGround: {
    asset: 'forest_ground_04',
    color: 0x737963,
    roughness: .94,
    metalness: 0,
    repeat: [12, 18],
    normalScale: 1.15,
    displacementScale: .42,
    displacementBias: -.1,
    wet: { roughness: .36, clearcoat: .28, envMapIntensity: .82 },
  },
  coastSand: {
    asset: 'coast_sand_02',
    color: 0xb8a88b,
    roughness: .88,
    metalness: 0,
    repeat: [9, 16],
    normalScale: .95,
    displacementScale: .28,
    displacementBias: -.06,
    wet: { roughness: .24, clearcoat: .55, envMapIntensity: 1.12 },
  },
  architecturalGlass: {
    color: 0xbcd8df,
    roughness: .08,
    metalness: .06,
    transmission: .55,
    thickness: .08,
    ior: 1.5,
    clearcoat: 1,
    envMapIntensity: 1.5,
  },
  paintedMetal: {
    color: 0x65727a,
    roughness: .26,
    metalness: .72,
    clearcoat: .52,
    envMapIntensity: 1.35,
  },
  foliage: {
    color: 0x315540,
    roughness: .82,
    metalness: 0,
    sheen: .18,
    sheenColor: 0x8bb39a,
    envMapIntensity: .55,
  },
};

export const SCENE_VIEWS = {
  // Look out from the right-hand building frontage instead of placing the
  // viewer over the road centreline. The target stays on the boulevard so
  // traffic and lane markings remain readable in the lower view.
  city: { position: [24, 26, 34], target: [-1, 15.5, -116], fog: .0022, fov: 56, lightTarget: [0, 16, -90], environment: [10, 26, -55] },
  alley: { position: [-20, 23, -208], target: [-46, 23, -246], fog: .0016, fov: 55, lightTarget: [-25, 16, -225], environment: [-20, 23, -208] },
  village: { position: [0, 8, 24], target: [0, 2, -30], fog: .0085, fov: 48, lightTarget: [0, 4, -32], environment: [0, 10, -24] },
  forest: { position: [0, 7, 20], target: [0, 3, -24], fog: .012, fov: 48, lightTarget: [0, 6, -42], environment: [0, 10, -28] },
  coast: { position: [0, 10, 25], target: [7, 2, -31], fog: .0065, fov: 48, lightTarget: [4, 3, -38], environment: [4, 12, -28] },
};

export const SCENE_PACK = {
  version: 2,
  style: 'contemporary-natural-realism',
  common: {
    camera: 'fixed-window-composition',
    lighting: 'analytic-sky-linear-pmrem-and-depth-gtao',
    lod: [
      { range: [0, 130], representation: 'scene-specific-pbr-architecture' },
      { range: [130, 280], representation: 'polyhaven-modular-lod2-and-1k-pbr' },
      { range: [280, 450], representation: 'helsinki-textured-city-mesh-lod2-and-atmospheric-fog' },
    ],
  },
  scenes: {
    city: {
      materials: ['roadSurface', 'asphalt', 'concrete', 'architecturalGlass', 'paintedMetal'],
      licensedAssets: [
        'polyhaven/modular_urban_apartments_facade',
        'polyhaven/modular_factory_facade',
        'polyhaven/modular_street_seating',
        'helsinki/textured-city-mesh-lod2',
      ],
      dynamic: ['traffic', 'windowLights', 'analyticSky', 'layeredClouds', 'wetGround', 'puddleReflection', 'rainImpacts'],
    },
    alley: {
      materials: ['concrete', 'architecturalGlass', 'paintedMetal'],
      licensedAssets: ['orca/bistro-exterior', 'polyhaven/modular_street_seating'],
      dynamic: ['streetLights', 'wetPavement', 'analyticSky', 'layeredClouds', 'awningAndFoliageWind', 'rainImpacts', 'puddleReflection'],
    },
    village: { materials: ['fieldSurface', 'wood', 'concrete', 'rock', 'foliage'], licensedAssets: ['polyhaven/grass_bermuda_01', 'polyhaven/grass_medium_02', 'polyhaven/modular_fort_01', 'polyhaven/wine_barrel_01', 'polyhaven/wooden_crate_02'], dynamic: ['wind', 'mist'] },
    forest: { materials: ['forestGround', 'wood', 'rock', 'foliage'], licensedAssets: ['polyhaven/mountainside', 'polyhaven/rock_moss_set_01', 'polyhaven/pine_sapling_small'], dynamic: ['wind', 'physicalStream'] },
    coast: { materials: ['coastSand', 'rock', 'wood', 'architecturalGlass'], licensedAssets: ['polyhaven/coast_line_01', 'polyhaven/sand_rocks_small_01', 'polyhaven/coastal_cliff_01', 'threejs/waternormals'], dynamic: ['planarReflectionOcean', 'shoreFoam'] },
  },
};
